batch_size: 2
num_workers: 0
data_path: "./content/competitions/11785-spring2021-hw2p2s1-face-classification/11785-spring2021-hw2p2s1-face-classification.zip"
unzip_path: "./content/sample_data"
train_data_path: "./content/sample_data/train_data"
val_data_path: "./content/sample_data/val_data"
shuffle: True
drop_last: True
learning_rate: 0.1
momentum: 0.9
nesterov: True
weight_decay: 0.00001
number_epochs: 80
augmentation:
  gaussian_blur_kernel_size: 5
  random_affine_degrees: 10
  # normalize_mean: (0.485, 0.456, 0.406)
  # normalize_std:  (0.229, 0.224, 0.225)
scheduler:
  mode: 'max'
  patience: 3
  threshold: 0.005
  factor: 0.1
  verbose: True


